# AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
version: '{build}'
skip_tags: true
clone_depth: 2
environment:
  matrix:
  # see https://www.appveyor.com/docs/linux-images-software/#ruby for list of installed Ruby runtimes
  - ruby_version: '26'
  - ruby_version: '26-x64'
  - ruby_version: '25'
  - ruby_version: '24'
  - ruby_version: '23'
init:
# Prepend Ruby path from matrix while removing original Ruby entry (C:\Ruby193\bin)
- set PATH=C:\Ruby%ruby_version%\bin;%PATH:C:\Ruby193\bin;=%
- echo %PATH%
- ruby -v
- gem -v
- bundler --version
install:
- bundle --jobs=3 --path=.bundle\gems
build_script:
- bundle exec rake build
test_script:
- bundle exec rake test:all
#artifacts:
#- path: pkg\*.gem
