language: ruby
sudo: false
rvm:
  - 2.2.1
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-head
  - jruby-19mode
  - jruby-18mode
  - rbx-2
script: bundle exec rake coverage test:all
notifications:
  email: false
  irc: 'irc.freenode.org#asciidoctor'
