sudo: false
git:
  depth: 1
language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-9.0.4.0
  - jruby-19mode
  - jruby-18mode
  - rbx-2
script: bundle exec rake coverage test:all
notifications:
  email: false
  irc: 'irc.freenode.org#asciidoctor'
